"""empty message

Revision ID: 0e9d2de47d13
Revises: d9d215e28816
Create Date: 2025-09-27 14:43:07.723766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0e9d2de47d13'
down_revision: Union[str, Sequence[str], None] = 'd9d215e28816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('starts_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ends_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_periods_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_periods_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_periods_name'))
        batch_op.drop_index(batch_op.f('ix_periods_id'))

    op.drop_table('periods')
    # ### end Alembic commands ###
