"""Fix timezone a Mexico Central

Revision ID: 2cfa6e64c03c
Revises: f354862ec8c9
Create Date: 2025-09-27 19:02:11.913588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfa6e64c03c'
down_revision: Union[str, Sequence[str], None] = 'f354862ec8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useraddresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useraddresses_created_at'))
        batch_op.drop_index(batch_op.f('ix_useraddresses_updated_at'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useraddresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useraddresses_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_useraddresses_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
