"""sku a SKU

Revision ID: 3c6d24fc4846
Revises: 7596f3bb2b74
Create Date: 2025-09-26 05:15:48.908750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3c6d24fc4846'
down_revision: Union[str, Sequence[str], None] = '7596f3bb2b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SKU', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
        batch_op.drop_column('sku')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('SKU')

    # ### end Alembic commands ###
