"""empty message

Revision ID: 482b19e9a1fe
Revises: 54e7e24da741
Create Date: 2025-09-25 09:05:31.449785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '482b19e9a1fe'
down_revision: Union[str, Sequence[str], None] = '54e7e24da741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_sponsor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['sponsor_id'], ['member_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_sponsor_id_fkey'), 'users', ['sponsor_id'], ['id'])

    # ### end Alembic commands ###
