"""empty message

Revision ID: 54e7e24da741
Revises: 0811dd4648ad
Create Date: 2025-09-24 21:54:33.485900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '54e7e24da741'
down_revision: Union[str, Sequence[str], None] = '0811dd4648ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertreepath',
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('sponsor_id', 'user_id')
    )
    with op.batch_alter_table('usertreepath', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usertreepath_level'), ['level'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usertreepath', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usertreepath_level'))

    op.drop_table('usertreepath')
    # ### end Alembic commands ###
