"""Se cambiaron algunos elementos de int a float

Revision ID: 7596f3bb2b74
Revises: e2e2c0a2fac5
Create Date: 2025-09-26 05:14:33.271261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7596f3bb2b74'
down_revision: Union[str, Sequence[str], None] = 'e2e2c0a2fac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
        batch_op.drop_column('SKU')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SKU', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
