"""Se eliminó columna level de usertreepaths

Revision ID: 7c68dc32ffad
Revises: fd47104175f5
Create Date: 2025-09-25 18:31:52.018336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7c68dc32ffad'
down_revision: Union[str, Sequence[str], None] = 'fd47104175f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usertreepath', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usertreepath_level'))
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usertreepath', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_usertreepath_level'), ['level'], unique=False)

    # ### end Alembic commands ###
