"""empty message

Revision ID: 9d383c49f617
Revises: 7c68dc32ffad
Create Date: 2025-09-25 18:57:29.755394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d383c49f617'
down_revision: Union[str, Sequence[str], None] = '7c68dc32ffad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usertreepath', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usertreepath_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('usertreepath_sponsor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['sponsor_id'], ['member_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['member_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usertreepath', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usertreepath_sponsor_id_fkey'), 'users', ['sponsor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('usertreepath_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
