"""add indexes to products

Revision ID: ad8d704c99f5
Revises: cba6f5780671
Create Date: 2026-01-10 23:59:05.875222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8d704c99f5'
down_revision: Union[str, Sequence[str], None] = 'cba6f5780671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_city'))
        batch_op.drop_index(batch_op.f('ix_addresses_country'))
        batch_op.drop_index(batch_op.f('ix_addresses_id'))
        batch_op.drop_index(batch_op.f('ix_addresses_neighborhood'))
        batch_op.drop_index(batch_op.f('ix_addresses_state'))
        batch_op.drop_index(batch_op.f('ix_addresses_street'))
        batch_op.drop_index(batch_op.f('ix_addresses_zip_code'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_SKU'), ['SKU'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_new'), ['is_new'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_presentation'), ['presentation'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_type'))
        batch_op.drop_index(batch_op.f('ix_products_presentation'))
        batch_op.drop_index(batch_op.f('ix_products_is_new'))
        batch_op.drop_index(batch_op.f('ix_products_SKU'))

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_zip_code'), ['zip_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_street'), ['street'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_neighborhood'), ['neighborhood'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_city'), ['city'], unique=False)

    # ### end Alembic commands ###
