"""Agregar campo country_cache a tabla users

Revision ID: b1341dba63d7
Revises: 3c6d24fc4846
Create Date: 2025-09-26 06:09:02.729095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b1341dba63d7'
down_revision: Union[str, Sequence[str], None] = '3c6d24fc4846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_cache', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_country_cache'), ['country_cache'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_country_cache'))
        batch_op.drop_column('country_cache')

    # ### end Alembic commands ###
