"""empty message

Revision ID: d085f33038f5
Revises: c86f3fcbb714
Create Date: 2025-09-22 09:35:37.862339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd085f33038f5'
down_revision: Union[str, Sequence[str], None] = 'c86f3fcbb714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialaccounts', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=postgresql.ENUM('FACEBOOK', 'INSTAGRAM', 'X', name='socialnetwork'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialaccounts', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=postgresql.ENUM('FACEBOOK', 'INSTAGRAM', 'X', name='socialnetwork'),
               nullable=False)

    # ### end Alembic commands ###
