"""empty message

Revision ID: e2e2c0a2fac5
Revises: 9d383c49f617
Create Date: 2025-09-26 05:05:46.666786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e2e2c0a2fac5'
down_revision: Union[str, Sequence[str], None] = '9d383c49f617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('presentation', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('pv_mx', sa.Integer(), nullable=False),
    sa.Column('pv_usa', sa.Integer(), nullable=False),
    sa.Column('pv_colombia', sa.Integer(), nullable=False),
    sa.Column('vn_mx', sa.Numeric(scale=2), nullable=True),
    sa.Column('vn_usa', sa.Numeric(scale=2), nullable=True),
    sa.Column('vn_colombia', sa.Numeric(scale=2), nullable=True),
    sa.Column('price_mx', sa.Numeric(scale=2), nullable=True),
    sa.Column('price_usa', sa.Numeric(scale=2), nullable=True),
    sa.Column('price_colombia', sa.Numeric(scale=2), nullable=True),
    sa.Column('public_mx', sa.Integer(), nullable=True),
    sa.Column('public_usa', sa.Integer(), nullable=True),
    sa.Column('public_colombia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_id'))

    op.drop_table('products')
    # ### end Alembic commands ###
