"""empty message

Revision ID: f354862ec8c9
Revises: 18e090f57c8d
Create Date: 2025-09-27 15:23:14.218425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f354862ec8c9'
down_revision: Union[str, Sequence[str], None] = '18e090f57c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrankhistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_userrankhistory_user_id'))
        batch_op.create_index(batch_op.f('ix_userrankhistory_member_id'), ['member_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('userrankhistory_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['member_id'], ['member_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrankhistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('userrankhistory_user_id_fkey'), 'users', ['user_id'], ['member_id'])
        batch_op.drop_index(batch_op.f('ix_userrankhistory_member_id'))
        batch_op.create_index(batch_op.f('ix_userrankhistory_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
