"""empty message

Revision ID: 36fa50c72185
Revises: 9cd6341dcf8b
Create Date: 2025-09-17 20:04:51.694413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '36fa50c72185'
down_revision: Union[str, Sequence[str], None] = '9cd6341dcf8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price_usa')
        batch_op.drop_column('price_mx')
        batch_op.drop_column('public_price_usa')
        batch_op.drop_column('vn_usa')
        batch_op.drop_column('public_price_colombia')
        batch_op.drop_column('price_colombia')
        batch_op.drop_column('presentation')
        batch_op.drop_column('vn_mx')
        batch_op.drop_column('public_price_mx')
        batch_op.drop_column('vn_colombia')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vn_colombia', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('public_price_mx', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vn_mx', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('presentation', postgresql.ENUM('Nanodispersión', 'Cápsulas', 'Serum', 'Crema', name='productpresentation'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_colombia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('public_price_colombia', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vn_usa', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('public_price_usa', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price_mx', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price_usa', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
